# Generated by Django 4.2.7 on 2023-11-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=255, verbose_name='Слоган')),
                ('center_mission', models.CharField(max_length=255, verbose_name='Місія центру')),
            ],
        ),
        migrations.CreateModel(
            name='SmallDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Маленький Мудрик - це...')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='mudryk.mainpageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonToChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Чому варто обрати?')),
                ('reason_to_choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons_to_choose', to='mudryk.mainpageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='InfoForParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Батькам (жирний шрифт)')),
                ('text', models.CharField(max_length=255, verbose_name='Батькам')),
                ('for_parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_for_parents', to='mudryk.mainpageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Знижки')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='mudryk.mainpageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Наші переваги')),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='mudryk.mainpageinfo')),
            ],
        ),
    ]
