# Generated by Django 4.2.7 on 2023-11-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageinfo',
            options={'ordering': ['id'], 'verbose_name': 'Головна сторінка', 'verbose_name_plural': 'Головна сторінка'},
        ),
    ]
