# Generated by Django 4.2.7 on 2023-11-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0002_alter_mainpageinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasontochoose',
            name='reason_to_choose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudryk.mainpageinfo'),
        ),
    ]
