# Generated by Django 4.2.7 on 2023-11-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0004_alter_reasontochoose_reason_to_choose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasontochoose',
            old_name='reason_to_choose',
            new_name='reason_to_choose_id',
        ),
    ]
