# Generated by Django 4.2.7 on 2023-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0006_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team_members/%Y/%m/%d'),
        ),
    ]
