# Generated by Django 4.2.7 on 2023-12-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0007_alter_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
            ],
            options={
                'verbose_name': 'Часте питання',
                'verbose_name_plural': 'Часті питання',
                'ordering': ['id'],
            },
        ),
    ]
