# Generated by Django 4.2.7 on 2023-12-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва курсу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TextWithListForCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('under_title', models.CharField(max_length=255, verbose_name="Підзаголовок (необов'язково)")),
                ('text_with_list_for_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_with_list_for_course', to='mudryk.course')),
            ],
        ),
        migrations.CreateModel(
            name='TextForCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст для заповнення курсу')),
                ('text_for_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_for_course', to='mudryk.course')),
            ],
        ),
        migrations.CreateModel(
            name='ListItemForText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст елемента списку')),
                ('list_item_for_text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_item_for_text', to='mudryk.course')),
            ],
        ),
    ]
