# Generated by Django 4.2.7 on 2023-12-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0010_alter_listitemfortext_list_item_for_text_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitemfortext',
            options={'ordering': ['id'], 'verbose_name': 'Елемент списка', 'verbose_name_plural': 'Елементи списка'},
        ),
        migrations.AlterModelOptions(
            name='textforcourse',
            options={'ordering': ['id'], 'verbose_name': 'Блок текста>', 'verbose_name_plural': 'Блоки текста'},
        ),
        migrations.AlterModelOptions(
            name='textwithlistforcourse',
            options={'ordering': ['id'], 'verbose_name': 'Блок текста зі списком', 'verbose_name_plural': 'Блоки текста зі списком'},
        ),
        migrations.AlterField(
            model_name='textforcourse',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст для заповнення курсу'),
        ),
        migrations.AlterField(
            model_name='textwithlistforcourse',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='textwithlistforcourse',
            name='under_title',
            field=models.CharField(blank=True, max_length=255, verbose_name="Підзаголовок (необов'язково)"),
        ),
    ]
