# Generated by Django 4.2.7 on 2023-12-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0011_alter_listitemfortext_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='textwithlistforcourse',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
