# Generated by Django 4.2.7 on 2023-12-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0012_alter_course_price_alter_textwithlistforcourse_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitemfortext',
            old_name='list_item_for_text_id',
            new_name='list_item_for_text',
        ),
        migrations.RenameField(
            model_name='textforcourse',
            old_name='text_for_course_id',
            new_name='text_for_course',
        ),
        migrations.RenameField(
            model_name='textwithlistforcourse',
            old_name='text_with_list_for_course_id',
            new_name='text_with_list_for_course',
        ),
        migrations.AlterField(
            model_name='textforcourse',
            name='text',
            field=models.TextField(blank=True, verbose_name="Текст для заповнення курсу (необов'язково)"),
        ),
    ]
