# Generated by Django 4.2.7 on 2023-12-17 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0013_rename_list_item_for_text_id_listitemfortext_list_item_for_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('feedback_text', models.TextField(verbose_name='Відгук')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефону повинен бути введений у такому форматі: 0639999999', regex='\\d{10}')])),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('proposal_text', models.TextField(verbose_name='Пропозиція')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефону повинен бути введений у такому форматі: 0639999999', regex='\\d{10}')])),
            ],
            options={
                'verbose_name': 'Пропозиція',
                'verbose_name_plural': 'Пропозиції',
                'ordering': ['id'],
            },
        ),
    ]
