# Generated by Django 4.2.7 on 2023-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0014_feedback_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Показувати на сайті:'),
        ),
    ]
