# Generated by Django 4.2.7 on 2023-12-17 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0015_feedback_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Дата створення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Показувати на сайті'),
        ),
    ]
