# Generated by Django 4.2.7 on 2023-12-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0018_remove_lesson_date_end_remove_lesson_date_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Посилання на Facebook сторінку')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Посилання на Instagram сторінку')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['id'], 'verbose_name': 'Запис', 'verbose_name_plural': 'Записи'},
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='mudryk.contact')),
            ],
            options={
                'verbose_name': 'Номер телефону',
                'verbose_name_plural': 'Номера телефонів',
                'ordering': ['id'],
            },
        ),
    ]
