# Generated by Django 4.2.7 on 2024-02-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudryk', '0020_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='lesson',
            field=models.CharField(default='', max_length=255, verbose_name='Урок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='surname',
            field=models.CharField(default='', max_length=255, verbose_name='Призвище'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
    ]
